default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: temp-graph_development

test:
  <<: *default
  database: temp-graph_test

production:
  <<: *default
  socket: /var/run/mysqld/mysql.sock
  database: temp-graph_production
  username: temp-graph
  password: <%= ENV['TEMP-GRAPH_DATABASE_PASSWORD'] %>
